### ISSUE TITLE
devops console doesn't work

### ISSUE THREAD

**Issue by cc901109** [kubesphere-extensions/ks-extensions#47]
I follow up README.md steps to modify the configmaps, but when I visit {materIP}:30180, the website doesn't work.

Below is my step:
1. In the extensions installation value.yaml, I edit these
```
  jenkins:
    securityRealm:
      openIdConnect:
        # The kubesphere-core api used for jenkins OIDC
        # If you want to access to jenkinsWebUI, the kubesphereCoreApi must be specified and browser-accessible
        # Modifying this configuration will take effect only during installation
        # If you wish for changes to take effect after installation, you need to update the jenkins-casc-config ConfigMap, copy the securityRealm configuration from jenkins.yaml to jenkins_user.yaml, save, and wait for approximately 70 seconds for the changes to take effect.
        kubesphereCoreApi: "http://172.1.30.252:30880"
        # The jenkins web URL used for OIDC redirect
        jenkinsURL: "http://172.1.30.252:30180"
```
2. Then, I edit in jenkins-casc-config
```
      securityRealm:
        oic:
          clientId: "jenkins"
          clientSecret: "jenkins"
          tokenServerUrl: "http://172.1.30.252:30880/oauth/token"
          authorizationServerUrl: "http://172.1.30.252:30880/oauth/authorize"
          userInfoServerUrl: "http://172.1.30.252:30880/oauth/userinfo"
          endSessionEndpoint: "http://172.1.30.252:30880/oauth/logout"
          logoutFromOpenidProvider: true
          scopes: openid profile email
          fullNameFieldName: url
          userNameField: preferred_username
```
3. Finally, I edit kubesphere-config 
```
authentication:
  issuer:
    url: "http://172.1.30.252:30880"
```

And I set up 1:1NAT, so visiting 10.63.22.252:30880 is correct, but 10.63.22.252:30180 cannot work.
How can I fix it?
